[package]
name = "rust_boi"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "lib_rust_boi"
path = "src/lib.rs"

[[bin]]
name = "rust_boi"
path = "src/main.rs"

[dependencies]
clap = "2.33.3"